###
GET http://{{hostname}}:{{port}}/api/v1

###
POST http://{{hostname}}:{{port}}/api/v1/slaves
Content-Type: application/json

[
  {
    "name": "slave3",
    "ip": "localhost",
    "port": 8081
  },
  {
    "name": "slave4",
    "ip": "localhost",
    "port": 8082
  }
]

###
GET http://{{hostname}}:{{port}}/api/v1/slaves

###
POST http://{{hostname}}:{{port}}/api/v1/creds
Content-Type: application/json

[
  {
    "description": "Test",
    "password": "123",
    "username": "user"
  },
  {
    "description": "Test",
    "password": "123",
    "username": "user1"
  },
  {
    "description": "Test",
    "password": "123",
    "username": "user2"
  }
]