basePath: /api/v1
definitions:
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  models.Health:
    properties:
      id:
        type: string
      port:
        type: integer
      status:
        $ref: '#/definitions/models.ServiceStatus'
    type: object
  models.ICredentialsCreate:
    properties:
      hash:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  models.IReadCredentials:
    properties:
      hash:
        type: string
      id:
        type: integer
      password:
        type: string
      username:
        type: string
    type: object
  models.IUpdateCredentials:
    properties:
      hash:
        type: string
      id:
        type: integer
      password:
        type: string
      username:
        type: string
    type: object
  models.ServerError:
    properties:
      error:
        type: string
    type: object
  models.ServiceStatus:
    enum:
    - 0
    - 1
    - 2
    - 3
    type: integer
    x-enum-varnames:
    - ONLINE
    - PENDING
    - ERROR
    - ShuttingDown
  models.SlaveDTO:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      ip:
        type: string
      name:
        type: string
      port:
        type: integer
      updatedAt:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  title: Brute Forcer API
  version: "1.0"
paths:
  /creds:
    delete:
      description: IDeleteParams credentials from the database
      parameters:
      - description: ID of the credentials to delete
        in: query
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ServerError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ServerError'
      summary: Delete credentials by ID
      tags:
      - Creds
    get:
      description: Get credentials from the database
      parameters:
      - description: Limit the number of results
        in: query
        name: limit
        type: integer
      - description: Offset number
        in: query
        name: page
        type: integer
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.IReadCredentials'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ServerError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ServerError'
      summary: Get credentials
      tags:
      - Creds
    post:
      consumes:
      - application/json
      description: Add credentials to the database
      parameters:
      - description: ICredentialsCreate
        in: body
        name: credentials
        required: true
        schema:
          items:
            $ref: '#/definitions/models.ICredentialsCreate'
          type: array
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.ICredentialsCreate'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ServerError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ServerError'
      summary: Add credentials
      tags:
      - Creds
  /health:
    get:
      description: API HealthCheck
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Health'
      summary: API Health Check
      tags:
      - Health Check
  /slaves:
    get:
      description: Get slaves from the database
      parameters:
      - description: Limit the number of results
        in: query
        name: limit
        type: integer
      - description: Offset number
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.SlaveDTO'
            type: array
        "400":
          description: Invalid request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get slaves
      tags:
      - Slaves
    post:
      consumes:
      - application/json
      description: Add slaves to the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.SlaveDTO'
            type: array
        "400":
          description: Invalid request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Add slaves
      tags:
      - Slaves
swagger: "2.0"
